import dotenv
import os

dotenv.load_dotenv()


PROJECT_ID = os.getenv("PROJECT_ID")
GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY")
SERVICE_ACCOUNT_FILE = os.getenv("SERVICE_ACCOUNT_FILE")
CALENDAR_SERVICE_ACCOUNT = os.getenv("CALENDAR_SERVICE_ACCOUNT")
GSHEETS_SERVICE_ACCOUNT = os.getenv("GSHEETS_SERVICE_ACCOUNT")
SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN")
APPOINTMENTS_SHEET_ID = os.getenv("APPOINTMENTS_SHEET_ID")
CLICKUP_API_TOKEN = os.getenv("CLICKUP_API_TOKEN")
CLICKUP_AVAILABILITY_LIST_ID = os.getenv("CLICKUP_AVAILABILITY_LIST_ID")
CLICKUP_CUSTOM_FIELD_CUSTOMER_ID = os.getenv("CLICKUP_CUSTOM_FIELD_CUSTOMER_ID")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")